// Mocks generated by Mockito 5.3.2 from annotations
// in sytex_coding_challenge/test/feature/form_feature/use_cases/get_answers_use_case.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sytex_coding_challenge/features/form_module/use_cases/get_form_questions_use_case/input_output/get_form_questions_output.dart'
    as _i2;
import 'package:sytex_coding_challenge/features/form_module/use_cases/get_form_questions_use_case/interactor/get_form_questions_use_case.dart'
    as _i3;
import 'package:sytex_coding_challenge/features/form_module/use_cases/get_form_questions_use_case/repositories/get_form_questions_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetFormQuestionsOutput_0 extends _i1.SmartFake
    implements _i2.GetFormQuestionsOutput {
  _FakeGetFormQuestionsOutput_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFormQuestionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFormQuestionsUseCase extends _i1.Mock
    implements _i3.GetFormQuestionsUseCase {
  @override
  _i4.Future<_i2.GetFormQuestionsOutput> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i4.Future<_i2.GetFormQuestionsOutput>.value(
            _FakeGetFormQuestionsOutput_0(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.GetFormQuestionsOutput>.value(
            _FakeGetFormQuestionsOutput_0(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i4.Future<_i2.GetFormQuestionsOutput>);
}

/// A class which mocks [GetFormQuestionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFormQuestionsRepository extends _i1.Mock
    implements _i5.GetFormQuestionsRepository {
  @override
  _i4.Future<_i2.GetFormQuestionsOutput> getGetFormQuestionsOutput() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGetFormQuestionsOutput,
          [],
        ),
        returnValue: _i4.Future<_i2.GetFormQuestionsOutput>.value(
            _FakeGetFormQuestionsOutput_0(
          this,
          Invocation.method(
            #getGetFormQuestionsOutput,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.GetFormQuestionsOutput>.value(
            _FakeGetFormQuestionsOutput_0(
          this,
          Invocation.method(
            #getGetFormQuestionsOutput,
            [],
          ),
        )),
      ) as _i4.Future<_i2.GetFormQuestionsOutput>);
}
